name: phobos::publish

on:
  release:
    types: [published]

jobs:
  publish-package-linux:
    name: phobos::compile::package-linux
    runs-on: ubuntu-latest

    steps:
      - name: phobos::compile::package-linux::Check out Git repository
        uses: actions/checkout@v3

      - name: phobos::compile::package-linux::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: phobos::compile::package-linux::Install Node.js dependencies
        run: npm ci

      - name: phobos::compile::package-linux::Compile
        run: npm run build

      - name: phobos::compile::package-linux::Publish
        run: npm run publish

  publish-package-macos:
    name: phobos::compile::package-macos
    runs-on: macOS-latest

    steps:
      - name: phobos::compile::package-macos::Check out Git repository
        uses: actions/checkout@v3

      - name: phobos::compile::package-macos::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: phobos::compile::package-macos::Install Node.js dependencies
        run: npm ci

      - name: phobos::compile::package-macos::Compile
        run: npm run build

      - name: phobos::compile::package-macos::Publish
        run: npm run publish

  publish-package-windows:
    name: phobos::compile::package-win
    runs-on: windows-latest

    steps:
      - name: phobos::compile::package-win::Check out Git repository
        uses: actions/checkout@v3

      - name: phobos::compile::package-win::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: phobos::compile::package-win::Install Node.js dependencies
        run: npm ci

      - name: phobos::compile::package-win::Compile
        run: npm run build

      - name: phobos::compile::package-win::Publish
        run: npm run publish
